name: Check

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  checks:
    name: Nix checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check formatting
        run: nix fmt -- --check .

      - name: Check flake
        run: nix flake check --all-systems --no-update-lock-file
